### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by LiangCyu1990** [Proofo/proofo-magento-2#1]
This issue don't related your projects. but I think, you are Magento hosting expert.
My hosting is shared hosting.
I worked with many Magento 2.3.3 files(upload and download).
Now I can't work because Disk quota exceeded.
Please help me.
Your Sincerely
![issue](https://user-images.githubusercontent.com/60872168/75945804-401ee400-5ed6-11ea-8261-cb432faf1839.png)

**Comment by imsamthomas** [comment]
Hi @LiangCyu1990 ,

You should remove unnecessary files, folder from your shared hosting.
Or find a the best hosting providers https://www.mageplaza.com/blog/magento-2-web-hosting.html
